// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Shared__CountriesController from "./shared/countries_controller"
application.register("shared--countries", Shared__CountriesController)

import Shared__ModalRequestController from "./shared/modal_request_controller"
application.register("shared--modal-request", Shared__ModalRequestController)

import Shared__TurboRequestController from "./shared/turbo_request_controller"
application.register("shared--turbo-request", Shared__TurboRequestController)

import Shared__VirtualSelectController from "./shared/virtual_select_controller"
application.register("shared--virtual-select", Shared__VirtualSelectController)
