// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Shared__AutocompleteController from "./shared/autocomplete_controller"
application.register("shared--autocomplete", Shared__AutocompleteController)

import Shared__ChoicesSelectController from "./shared/choices_select_controller"
application.register("shared--choices-select", Shared__ChoicesSelectController)

import Shared__CountriesController from "./shared/countries_controller"
application.register("shared--countries", Shared__CountriesController)

import Shared__MapBoxController from "./shared/map_box_controller"
application.register("shared--map-box", Shared__MapBoxController)

import Shared__ModalController from "./shared/modal_controller"
application.register("shared--modal", Shared__ModalController)

import Shared__TurboRequestController from "./shared/turbo_request_controller"
application.register("shared--turbo-request", Shared__TurboRequestController)

import Shared__VirtualSelectController from "./shared/virtual_select_controller"
application.register("shared--virtual-select", Shared__VirtualSelectController)

