// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import Shared__ModalRequestController from "./shared/modal_request_controller.js"
application.register("shared--modal-request", Shared__ModalRequestController)

import Shared__TurboRequestController from "./shared/turbo_request_controller.js"
application.register("shared--turbo-request", Shared__TurboRequestController)
