default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: planify_development

test:
  <<: *default
  database: planify_test

staging:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  sslmode: <%= ENV['DATABASE_SSLMODE'] %>

production:
  <<: *default
  database: planify_production
  username: deploy
  password: <%= ENV['STARTER_TEMPLATE_DATABASE_PASSWORD'] %>
