name: "App CI"

on:
  pull_request:
    branches: ['staging', 'main']

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  Dependencies:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://planify:password@localhost:5432/planify_test

    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: planify_test
          POSTGRES_USER: planify
          POSTGRES_PASSWORD: password

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16.14'

      - name: Install ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Setup database
        run: bin/rails db:schema:load

      - name: Install JS dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

  Tests:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://planify:password@localhost:5432/planify_test

    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: planify_test
          POSTGRES_USER: planify
          POSTGRES_PASSWORD: password

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Setup database
        run: bin/rails db:schema:load

      - name: Run tests
        run: bundle exec rspec

  Linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop
